In [1]:
import pandas as pd
import numpy as np

In [14]:
New_weather_steps = pd.read_csv("New_weather_steps.csv")
New_weather_steps = New_weather_steps.drop("Unnamed: 0",axis=1)
display(New_weather_steps)

,start,steps,direction_wind,windspeed_avg_hour,windspeed_avg_10min,max_wind_gust,temp_celsius,temp_min_6h,temp_dewpoint,sunshine_duration,...,cloud_cover,relative_humidity,weather_code,indicator_present_weather_code,fog,rain,snow,thunder,ice_formation,int_steps
0,2023-01-01 00:00:00,0.000000,220.0,110.0,130.0,200.0,142.0,NaN,84.0,0.0,...,8.0,68.0,NaN,5,0.0,0.0,0.0,0.0,0.0,0
1,2023-01-01 00:10:00,97.054054,220.0,110.0,130.0,200.0,142.0,NaN,84.0,0.0,...,8.0,68.0,NaN,5,0.0,0.0,0.0,0.0,0.0,97
2,2023-01-01 00:20:00,94.945946,220.0,110.0,130.0,200.0,142.0,NaN,84.0,0.0,...,8.0,68.0,NaN,5,0.0,0.0,0.0,0.0,0.0,94
3,2023-01-01 00:30:00,0.000000,220.0,110.0,130.0,200.0,142.0,NaN,84.0,0.0,...,8.0,68.0,NaN,5,0.0,0.0,0.0,0.0,0.0,0
4,2023-01-01 00:40:00,46.876667,220.0,110.0,130.0,200.0,142.0,NaN,84.0,0.0,...,8.0,68.0,NaN,5,0.0,0.0,0.0,0.0,0.0,46
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22460,2023-06-05 23:20:00,0.000000,10.0,60.0,60.0,80.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,6,NaN,NaN,NaN,NaN,NaN,0
22461,2023-06-05 23:30:00,0.000000,10.0,60.0,60.0,80.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,6,NaN,NaN,NaN,NaN,NaN,0
22462,2023-06-05 23:40:00,0.000000,10.0,60.0,60.0,80.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,6,NaN,NaN,NaN,NaN,NaN,0
22463,2023-06-05 23:50:00,0.000000,10.0,60.0,60.0,80.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,6,NaN,NaN,NaN,NaN,NaN,0
22464,2023-06-06 00:00:00,0.000000,360.0,20.0,20.0,30.0,95.0,NaN,82.0,0.0,...,NaN,91.0,NaN,6,NaN,NaN,NaN,NaN,NaN,0

In [15]:
New_weather_steps['temp_celsius'] = New_weather_steps['temp_celsius'].interpolate()
display(New_weather_steps.iloc[:15])

,start,steps,direction_wind,windspeed_avg_hour,windspeed_avg_10min,max_wind_gust,temp_celsius,temp_min_6h,temp_dewpoint,sunshine_duration,...,cloud_cover,relative_humidity,weather_code,indicator_present_weather_code,fog,rain,snow,thunder,ice_formation,int_steps
0,2023-01-01 00:00:00,0.000000,220.0,110.0,130.0,200.0,142.000000,NaN,84.0,0.0,...,8.0,68.0,NaN,5,0.0,0.0,0.0,0.0,0.0,0
1,2023-01-01 00:10:00,97.054054,220.0,110.0,130.0,200.0,142.000000,NaN,84.0,0.0,...,8.0,68.0,NaN,5,0.0,0.0,0.0,0.0,0.0,97
2,2023-01-01 00:20:00,94.945946,220.0,110.0,130.0,200.0,142.000000,NaN,84.0,0.0,...,8.0,68.0,NaN,5,0.0,0.0,0.0,0.0,0.0,94
3,2023-01-01 00:30:00,0.000000,220.0,110.0,130.0,200.0,142.000000,NaN,84.0,0.0,...,8.0,68.0,NaN,5,0.0,0.0,0.0,0.0,0.0,0
4,2023-01-01 00:40:00,46.876667,220.0,110.0,130.0,200.0,142.000000,NaN,84.0,0.0,...,8.0,68.0,NaN,5,0.0,0.0,0.0,0.0,0.0,46
5,2023-01-01 00:50:00,126.326232,220.0,110.0,130.0,200.0,142.000000,NaN,84.0,0.0,...,8.0,68.0,NaN,5,0.0,0.0,0.0,0.0,0.0,126
6,2023-01-01 01:00:00,128.406776,220.0,160.0,150.0,200.0,139.714286,NaN,NaN,NaN,...,NaN,NaN,NaN,6,NaN,NaN,NaN,NaN,NaN,128
7,2023-01-01 01:10:00,26.821821,220.0,160.0,150.0,200.0,137.428571,NaN,NaN,NaN,...,NaN,NaN,NaN,6,NaN,NaN,NaN,NaN,NaN,26
8,2023-01-01 01:20:00,0.000000,220.0,160.0,150.0,200.0,135.142857,NaN,NaN,NaN,...,NaN,NaN,NaN,6,NaN,NaN,NaN,NaN,NaN,0
9,2023-01-01 01:30:00,94.514644,220.0,160.0,150.0,200.0,132.857143,NaN,NaN,NaN,...,NaN,NaN,NaN,6,NaN,NaN,NaN,NaN,NaN,94
10,2023-01-01 01:40:00,83.035725,220.0,160.0,150.0,200.0,130.571429,NaN,NaN,NaN,...,NaN,NaN,NaN,6,NaN,NaN,NaN,NaN,NaN,83
11,2023-01-01 01:50:00,1.945755,220.0,160.0,150.0,200.0,128.285714,NaN,NaN,NaN,...,NaN,NaN,NaN,6,NaN,NaN,NaN,NaN,NaN,1
12,2023-01-01 02:00:00,0.000000,210.0,140.0,130.0,170.0,126.000000,NaN,77.0,0.0,...,8.0,72.0,NaN,5,0.0,0.0,0.0,0.0,0.0,0
13,2023-01-01 02:10:00,117.962963,210.0,140.0,130.0,170.0,126.000000,NaN,77.0,0.0,...,8.0,72.0,NaN,5,0.0,0.0,0.0,0.0,0.0,117
14,2023-01-01 02:20:00,134.037037,210.0,140.0,130.0,170.0,126.000000,NaN,77.0,0.0,...,8.0,72.0,NaN,5,0.0,0.0,0.0,0.0,0.0,134