In [17]:
import pandas as pd

#Create df
weather_steps = pd.read_csv("weather_steps.csv")
weather_steps = weather_steps.drop(weather_steps.columns[0], axis=1)
display(weather_steps)

,creationDate,hour,value,windspeed_avg_hour,windspeed_avg_10min,max_wind_gust,temp_celsius,temp_min_6h,temp_dewpoint,sunshine_duration,...,horizontal_visibility,cloud_cover,relative_humidity,weather_code,indicator_present_weather_code,fog,rain,snow,thunder,ice_formation
0,2023-01-01 00:25:48 +0200,00:00:00,171,110.0,130.0,200.0,142.0,NaN,84.0,0.0,...,66.0,8.0,68.0,NaN,5,0.0,0.0,0.0,0.0,0.0
1,2023-01-01 00:35:44 +0200,00:00:00,18,110.0,130.0,200.0,142.0,NaN,84.0,0.0,...,66.0,8.0,68.0,NaN,5,0.0,0.0,0.0,0.0,0.0
2,2023-01-01 00:39:25 +0200,00:00:00,3,110.0,130.0,200.0,142.0,NaN,84.0,0.0,...,66.0,8.0,68.0,NaN,5,0.0,0.0,0.0,0.0,0.0
3,2023-01-01 00:55:33 +0200,00:00:00,82,110.0,130.0,200.0,142.0,NaN,84.0,0.0,...,66.0,8.0,68.0,NaN,5,0.0,0.0,0.0,0.0,0.0
4,2023-01-01 01:04:25 +0200,00:00:00,12,110.0,130.0,200.0,142.0,NaN,84.0,0.0,...,66.0,8.0,68.0,NaN,5,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7764,2023-06-06 08:37:36 +0200,08:00:00,221,30.0,30.0,60.0,183.0,NaN,117.0,10.0,...,NaN,NaN,65.0,NaN,6,NaN,NaN,NaN,NaN,NaN
7765,2023-06-06 09:00:07 +0200,08:00:00,1108,30.0,30.0,60.0,183.0,NaN,117.0,10.0,...,NaN,NaN,65.0,NaN,6,NaN,NaN,NaN,NaN,NaN
7766,2023-06-06 09:00:20 +0200,08:00:00,1113,30.0,30.0,60.0,183.0,NaN,117.0,10.0,...,NaN,NaN,65.0,NaN,6,NaN,NaN,NaN,NaN,NaN
7767,2023-06-06 09:15:01 +0200,09:00:00,137,90.0,90.0,110.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,6,NaN,NaN,NaN,NaN,NaN
7768,2023-06-06 09:10:53 +0200,09:00:00,150,90.0,90.0,110.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,6,NaN,NaN,NaN,NaN,NaN

In [14]:
print(weather_steps.isna().sum())
#remove temp_min_6h and weather_code, because they contain more than 80% missing values    
weather_steps = weather_steps.drop(["temp_min_6h", "weather_code"] , axis=1)

creationDate                         0
hour                                 0
value                                0
windspeed_avg_hour                 158
windspeed_avg_10min                158
max_wind_gust                      158
temp_celsius                      2287
temp_min_6h                       6826
temp_dewpoint                     2287
sunshine_duration                 2555
glob_radiation                    2555
precipitation_duration            2417
precipitation_amount_hourly       2417
air_pressure                      3971
horizontal_visibility             3791
cloud_cover                       4610
relative_humidity                 2287
weather_code                      6447
indicator_present_weather_code       0
fog                               3791
rain                              3791
snow                              3791
thunder                           3791
ice_formation                     3791
dtype: int64

In [15]:
# Convert the 'time' column to datetime
weather_steps['creationDate'] = pd.to_datetime(weather_steps['creationDate'], format='%Y-%m-%d %H:%M')

# Interpolate the missing values
weather_steps['windspeed_avg_hour'] = weather_steps['windspeed_avg_hour'].interpolate()
weather_steps['windspeed_avg_10min'] = weather_steps['windspeed_avg_10min'].interpolate()
weather_steps['max_wind_gust'] = weather_steps['max_wind_gust'].interpolate()
weather_steps['temp_celsius'] = weather_steps['temp_celsius'].interpolate()
weather_steps['temp_dewpoint'] = weather_steps['temp_dewpoint'].interpolate()
weather_steps['sunshine_duration'] = weather_steps['sunshine_duration'].interpolate()
weather_steps['glob_radiation'] = weather_steps['glob_radiation'].interpolate()
weather_steps['precipitation_duration'] = weather_steps['precipitation_duration'].interpolate()
weather_steps['precipitation_amount_hourly'] = weather_steps['precipitation_amount_hourly'].interpolate()
weather_steps['air_pressure'] = weather_steps['air_pressure'].interpolate()
weather_steps['horizontal_visibility'] = weather_steps['horizontal_visibility'].interpolate()
weather_steps['cloud_cover'] = weather_steps['cloud_cover'].interpolate()
weather_steps['relative_humidity'] = weather_steps['relative_humidity'].interpolate()
weather_steps['fog'] = weather_steps['fog'].interpolate()
weather_steps['rain'] = weather_steps['rain'].interpolate()
weather_steps['snow'] = weather_steps['snow'].interpolate()
weather_steps['thunder'] = weather_steps['thunder'].interpolate()
weather_steps['ice_formation'] = weather_steps['ice_formation'].interpolate()

In [18]:
display(weather_steps.iloc[:30])

,creationDate,hour,value,windspeed_avg_hour,windspeed_avg_10min,max_wind_gust,temp_celsius,temp_min_6h,temp_dewpoint,sunshine_duration,...,horizontal_visibility,cloud_cover,relative_humidity,weather_code,indicator_present_weather_code,fog,rain,snow,thunder,ice_formation
0,2023-01-01 00:25:48 +0200,00:00:00,171,110.0,130.0,200.0,142.0,NaN,84.0,0.0,...,66.0,8.0,68.0,NaN,5,0.0,0.0,0.0,0.0,0.0
1,2023-01-01 00:35:44 +0200,00:00:00,18,110.0,130.0,200.0,142.0,NaN,84.0,0.0,...,66.0,8.0,68.0,NaN,5,0.0,0.0,0.0,0.0,0.0
2,2023-01-01 00:39:25 +0200,00:00:00,3,110.0,130.0,200.0,142.0,NaN,84.0,0.0,...,66.0,8.0,68.0,NaN,5,0.0,0.0,0.0,0.0,0.0
3,2023-01-01 00:55:33 +0200,00:00:00,82,110.0,130.0,200.0,142.0,NaN,84.0,0.0,...,66.0,8.0,68.0,NaN,5,0.0,0.0,0.0,0.0,0.0
4,2023-01-01 01:04:25 +0200,00:00:00,12,110.0,130.0,200.0,142.0,NaN,84.0,0.0,...,66.0,8.0,68.0,NaN,5,0.0,0.0,0.0,0.0,0.0
5,2023-01-01 01:07:29 +0200,00:00:00,88,110.0,130.0,200.0,142.0,NaN,84.0,0.0,...,66.0,8.0,68.0,NaN,5,0.0,0.0,0.0,0.0,0.0
6,2023-01-01 01:04:25 +0200,00:00:00,14,110.0,130.0,200.0,142.0,NaN,84.0,0.0,...,66.0,8.0,68.0,NaN,5,0.0,0.0,0.0,0.0,0.0
7,2023-01-01 01:04:25 +0200,00:00:00,38,110.0,130.0,200.0,142.0,NaN,84.0,0.0,...,66.0,8.0,68.0,NaN,5,0.0,0.0,0.0,0.0,0.0
8,2023-01-01 01:04:25 +0200,00:00:00,6,110.0,130.0,200.0,142.0,NaN,84.0,0.0,...,66.0,8.0,68.0,NaN,5,0.0,0.0,0.0,0.0,0.0
9,2023-01-01 01:04:25 +0200,01:00:00,35,160.0,150.0,200.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,6,NaN,NaN,NaN,NaN,NaN
10,2023-01-01 01:17:54 +0200,01:00:00,73,160.0,150.0,200.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,6,NaN,NaN,NaN,NaN,NaN
11,2023-01-01 01:18:01 +0200,01:00:00,62,160.0,150.0,200.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,6,NaN,NaN,NaN,NaN,NaN
12,2023-01-01 01:43:15 +0200,01:00:00,98,160.0,150.0,200.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,6,NaN,NaN,NaN,NaN,NaN
13,2023-01-01 01:47:16 +0200,01:00:00,136,160.0,150.0,200.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,6,NaN,NaN,NaN,NaN,NaN
14,2023-01-01 01:59:14 +0200,01:00:00,33,160.0,150.0,200.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,6,NaN,NaN,NaN,NaN,NaN
15,2023-01-01 02:22:32 +0200,02:00:00,130,140.0,130.0,170.0,126.0,NaN,77.0,0.0,...,74.0,8.0,72.0,NaN,5,0.0,0.0,0.0,0.0,0.0
16,2023-01-01 02:32:07 +0200,02:00:00,122,140.0,130.0,170.0,126.0,NaN,77.0,0.0,...,74.0,8.0,72.0,NaN,5,0.0,0.0,0.0,0.0,0.0
17,2023-01-01 02:41:39 +0200,02:00:00,113,140.0,130.0,170.0,126.0,NaN,77.0,0.0,...,74.0,8.0,72.0,NaN,5,0.0,0.0,0.0,0.0,0.0
18,2023-01-01 02:59:42 +0200,02:00:00,102,140.0,130.0,170.0,126.0,NaN,77.0,0.0,...,74.0,8.0,72.0,NaN,5,0.0,0.0,0.0,0.0,0.0
19,2023-01-01 03:09:44 +0200,02:00:00,227,140.0,130.0,170.0,126.0,NaN,77.0,0.0,...,74.0,8.0,72.0,NaN,5,0.0,0.0,0.0,0.0,0.0
20,2023-01-01 03:18:49 +0200,03:00:00,48,90.0,100.0,160.0,130.0,NaN,75.0,0.0,...,NaN,NaN,69.0,NaN,6,NaN,NaN,NaN,NaN,NaN
21,2023-01-01 03:19:34 +0200,03:00:00,416,90.0,100.0,160.0,130.0,NaN,75.0,0.0,...,NaN,NaN,69.0,NaN,6,NaN,NaN,NaN,NaN,NaN
22,2023-01-01 03:31:53 +0200,03:00:00,58,90.0,100.0,160.0,130.0,NaN,75.0,0.0,...,NaN,NaN,69.0,NaN,6,NaN,NaN,NaN,NaN,NaN
23,2023-01-01 03:45:54 +0200,03:00:00,42,90.0,100.0,160.0,130.0,NaN,75.0,0.0,...,NaN,NaN,69.0,NaN,6,NaN,NaN,NaN,NaN,NaN
24,2023-01-01 03:44:35 +0200,03:00:00,79,90.0,100.0,160.0,130.0,NaN,75.0,0.0,...,NaN,NaN,69.0,NaN,6,NaN,NaN,NaN,NaN,NaN
25,2023-01-01 03:56:43 +0200,03:00:00,42,90.0,100.0,160.0,130.0,NaN,75.0,0.0,...,NaN,NaN,69.0,NaN,6,NaN,NaN,NaN,NaN,NaN
26,2023-01-01 04:08:56 +0200,03:00:00,140,90.0,100.0,160.0,130.0,NaN,75.0,0.0,...,NaN,NaN,69.0,NaN,6,NaN,NaN,NaN,NaN,NaN
27,2023-01-01 04:10:25 +0200,03:00:00,196,90.0,100.0,160.0,130.0,NaN,75.0,0.0,...,NaN,NaN,69.0,NaN,6,NaN,NaN,NaN,NaN,NaN
28,2023-01-01 04:18:58 +0200,04:00:00,11,90.0,80.0,120.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,6,NaN,NaN,NaN,NaN,NaN
29,2023-01-01 04:19:44 +0200,04:00:00,242,90.0,80.0,120.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,6,NaN,NaN,NaN,NaN,NaN